version: 0.2

phases:
  install:
    runtime-versions:
      python: latest
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - '**/*'
