version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8  # Not really used here
    commands:
      - echo "Nothing to install"
  build:
    commands:
      - echo "No build step needed"
artifacts:
  files:
    - index.html
    - appspec.yml
    - scripts/**/* 
