version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
  build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.py
    - appspec.yml
    - scripts/*
buildspec.yml
